spring:
  application:
    name: auth-server
server:
  port: 7777
  servlet:
    contextPath: /auth
eureka:
  client:
    serviceUrl:
      defaultZone: http://p2:1112/eureka/,http://p1:1111/eureka/
  instance:
    prefer-ip-address: true