eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    appname: service-zuul
server:
  port: 9998

#zuul:
#  host:
#    connect-timeout-millis: 60000
#    socket-timeout-millis: 60000

#ribbon:
#  ReadTimeout: 7000 #超时时间
#  ConnectTimeout: 2000 #连接时间
#  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
#  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
#  OkToRetryOnAllOperations: false  #是否所有操作都重试
#
##解决hystrix+feign超时设置
#feign:
#  hystrix: #开启feign支持hystrix (注意:一定要开启，旧版本默认支持，新版本默认关闭)
#    enabled: true
#
#
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds:7000
#            ribbon:
#              ReadTimeout:1000
#              ConnectTimeout:1000

